server:
  port: 7090
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
eureka:
  client:
    #是否向注册中心注册自己，缺省：true
    register-with-eureka: true
    #是否从Eureka获取注册信息，。缺省：true
    fetch-registry: true
    #Eureka服务器的地址
    service-url:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/
  instance:
    prefer-ip-address: true
    #定于服务失效的时间（即server端多长时间没收到心跳后就将此实例剔除)，默认为90秒
    lease-expiration-duration-in-seconds: 90
    #定义服务续约任务的调用时间间隔（即发送心跳给server端的频率），默认为30秒
    lease-renewal-interval-in-seconds: 30