server:
  port: 9090
  tomcat:
    max-connections: 10
spring:
  application:
    name: user-service
logging:
  level:
   root: info
   com.zhxfun.client.ItemService: debug
eureka:
  client:
    #是否向注册中心注册自己，缺省：true
    register-with-eureka: true
    #是否从Eureka获取注册信息，。缺省：true
    fetch-registry: true
    #Eureka服务器的地址
    service-url:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/
  instance:
    prefer-ip-address: true
    #定于服务失效的时间（即server端多长时间没收到心跳后就将此实例剔除)，默认为90秒
    lease-expiration-duration-in-seconds: 90
    #定义服务续约任务的调用时间间隔（即发送心跳给server端的频率），默认为30秒
    lease-renewal-interval-in-seconds: 30
ribbon:
  #Ribbon实现负载均衡算法配置，前面的key是固定写法，后面是负载均衡算法的全路径
# NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
  #指的是建立连接所用的时间，适用于网络状况正常的情况下，俩端连接所用的时间 单位是秒
  connectTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源的时间
  readTimeout: 5000
  #对所有操作请求都进行重试
# OkToRetryOnAllOperations: true
  #切换实例的重试次数
# MaxAutoRetriesNextServer: 2
  #对当前实例的重试次数
# MaxAutoRetries: 1
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
              timeoutInMilliseconds: 3000
  dashboard:
      proxy-stream-allow-list: "localhost"
feign:
  client:
    config:
      default:
        loggerLevel: FULL
        connectTimeout: 5000
        readTimeout: 5000
  hystrix:
    enabled: true
