server:
  port: 9001
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          #  配置文件只搜索url目录下的searchPaths
          uri: https://github.com/zhxfun/spring-cloud-learning.git
          # 对应 {label} 部分，即 Git 的分支
          defaultLabel: main
          # 指定搜索路径，如果有多个路径则使用,分隔
          search-paths: config-learning/config-repo
          # 对于使用git,svn做为后端配置，从远程库获取配置文件，需要存储到本地文件
          basedir: /tmp/config-repo
          # 配置中心通过git从远程git库，有时本地的拷贝被污染，这时配置中心无法从远程库更新本地配置,设置force-pull=true，则强制从远程库中更新本地库
          force-pull: true
          # git 仓库用户名（公开库可以不用填写）
          username: zhxfun
          # git 仓库密码（公开库可以不用填写）
          password: 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
